[project]
name = "h3test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["aioquic>=1.2.0"]

[tool.isort]
profile = "black"
