name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Run Black (code formatting check)
        run: |
          uv run black --check --diff .

      - name: Run isort (import sorting check)
        run: |
          uv run isort --check-only --diff .

      - name: Run flake8 (linting)
        run: |
          uv run flake8 .

      - name: Run mypy (type checking)
        run: |
          uv run mypy .
