name: Publish to PyPI

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v1.0.0, v1.2.3, etc.

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.13

      - name: Extract version from tag
        id: version
        run: |
          # Extract version from tag (remove 'v' prefix if present)
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Update version in __init__.py
        run: |
          # Update the version in __init__.py to match the tag
          sed -i 's/__version__ = ".*"/__version__ = "${{ steps.version.outputs.version }}"/' quic_migration_tester/__init__.py
          echo "Updated version in __init__.py:"
          grep "__version__" quic_migration_tester/__init__.py

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Run tests
        run: |
          uv run black --check .
          uv run isort --check-only .
          uv run flake8 .
          uv run mypy .

      - name: Build package
        run: |
          uv build

      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv publish
